[project]
name = "Customer-Care-RAG-Chatbot"
description = "AI-powered Telecom Customer Care Assistant using RAG, LangChain, ChromaDB, HuggingFace Embeddings, and Groq Qwen3-32B for intelligent customer support."
requires-python = ">=3.11"
dependencies = [
    "langchain",
    "langchain-core",
    "langchain-chroma",
    "langchain-groq",
    "langchain-huggingface",
    "chromadb",
    "sentence-transformers",
    "pandas",
    "python-dotenv",
    "streamlit",
    "fpdf2",
    "pypdf",
    "langchain-community",
    "langchain-text-splitters",
]
